#! /bin/sh

sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

bspc config border_width         6
bspc config window_gap           8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config click_to_focus 	 	  true
bspc config focus_follows_pointer true

bspc config normal_border_color "#2f343f"
bspc config active_border_color "#bf616a"
bspc config focused_border_color "#bf616a"
bspc config presel_feedback_color "#bf616a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
